#! /bin/sh

########## BSPWM ###########
bspc monitor -d 1 2 3 4

bspc config normal_border_color 	"#f1d4d4"
bspc config active_border_color 	"#f1d4d4"
bspc config focused_border_color 	"#484c7f"

bspc config border_width         	2
bspc config window_gap          	24

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer 	false
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

########## STARTUP ###########
sxhkd -c ~/.config/sxhkd/sxhkdrc &
picom --config ~/.config/compton.conf.purp &
feh --bg-fill ~/Pictures/Wallpaper/games/touhou-classic-art/1.png &
xsetroot -cursor_name left_ptr &
polybar -c ~/.config/polybar/config purp &
setxkbmap -option caps:swapescape  &
dunst -config ~/.config/dunst/dunstrc-purp &
xrdb ~/.Xresources_purp &
redshift -x -PO 5600 &
sleep 2
~/.scripts/tewi-fortune.sh &
pulseaudio -D &
